### PR TITLE
feat: add favicon and og image

### PR DESCRIPTION
**Pull request by jeromeandrewong**
added og image [(fil- based)](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/opengraph-image#image-files-jpg-png-gif) and favicon
cant seem to test og image on preview branches but the meta tags are there when we inspect the page

### CODE REVIEW

**Comment by davidlhw** [comment]
seems like we're not able to see ogimage previews on these links because nextauth demand that visitors to the ogimage url be authenticated

after digging a little deeper, it seems we might not need a configuration pattern like "auth for all pages except xyz", but should instead go for "auth required for pages abc"

let's update middleware to only require auth for the path `/submit` for now. the other pages can handle auth sessions individually, either by allowing partial content, or by appending the route to the middleware matched

cc @Jaylin0312

**Review by davidlhw — COMMENTED** [review]
thanks for the PR!

seems good aside from the auth middleware

we might want to think of using dynamically generated ogimages in the future alongside introduction of #127

maybe with the use of [`vercel/og`](https://vercel.com/docs/functions/og-image-generation)

**Comment by jeromeandrewong** [comment]
> seems like we're not able to see ogimage previews on these links because nextauth demand that visitors to the ogimage url be authenticated (favicon works for me, likely cause it was excluded in nextauth)
> 
> after digging a little deeper, it seems we might not need a configuration pattern like "auth for all pages except xyz", but should instead go for "auth required for pages abc"
> 
> let's update middleware to only require auth for the path `/submit` for now. the other pages can handle auth sessions individually, either by allowing partial content, or by appending the route to the middleware matched
> 
> cc @Jaylin0312

thanks for investigating, made the change to our middleware and checked that og image is working using [linkedin post inspector](https://www.linkedin.com/post-inspector/)
CleanShot 2024-06-07 at 11 12 23@2x

**Review by davidlhw — APPROVED** [review]
CLGTM @ f48074e0459e1394b721b7dbe497d1ef0cf9607b!

**Pull request merged**
