### PR TITLE
chore: migrate to app router with next@14

### LINKED ISSUE #28: [Build][Feat] Migrate to T3 + App router
## Features

Create-T3-App now supports [App Router](https://nextjs.org/docs/app) - [explainer video](https://youtu.be/PmBfq-SpzCU)

### Core

- Migrate all pages to use `/app` instead of `/page`

## Implementation

- Nextjs [App Routing fundamentals](https://nextjs.org/docs/app/building-your-application/routing)
- [Reference repo](https://github.com/t3-oss/create-t3-app/tree/next/upgrade/src) for t3-app with app router

## Potential Issues

- Migrating to app will require quite abit of work as consideration needs to be made to consider which part of the app will be server or client side

### PR DESCRIPTION
**Pull request by DavidLHW**
closes #28

## changes

- upgraded packages
- migrated to app router
- removed `<PageHead />`, to use [`metadata`](https://nextjs.org/docs/app/building-your-application/optimizing/metadata) instead
- extracted `ThemeProvider` and `AuthProvider` into it's own [independent files](https://github.com/AfterClass-io/afterclass.io-v2/blob/chore/next-app-router/src/common/providers)
- fix `WarningCircleIcon`'s `fill-rule` -> `fillRule` and `clip-rule` -> `clipRule`

## preview

preview

### CODE REVIEW

**Review by Aztriltus — COMMENTED** [review]
Should we make the `/src` folder cleaner?

I'm thinking we can move your `trpc` and `utils` folder into `src/common`. This way, when developers choose a folder, they either choose `common`, `modules`, `app` or `server` to develop on. 

Maybe something like 

```
src/common
- /tools/trpc
- /tools/trpc/utils
```

What do you think?

**Comment by Aztriltus** [comment]
https://github.com/AfterClass-io/afterclass.io-v2/assets/6003064/a7736c11-b5b6-4d6d-8563-b352ab174b56

Also 404 works fine for me

**Review by Aztriltus — APPROVED** [review]
Nice, no issues for me now. LGTM

**Review by jeromeandrewong — APPROVED** [review]
LGTM! However,  is `metadata = {}` in `/app/layout.tsx` configured yet to replace `<PageHead />`?  Not sure if you want to create a separate issue for that

**Review by jeromeandrewong — DISMISSED** [review]
thanks for the changes! LGTM

**Review by jeromeandrewong — APPROVED** [review]
LGTM

**Review by Jaylin0312 — APPROVED** [review]
Tested on both prod and local, works as expected! Thanks for the PR :))

**Pull request merged**
